---
title: "STAT 345 Midterm Project"
author: "Saulai Vue"
date: "2025-04-01"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE, warning=FALSE}
library(dslabs)
library(tidyverse)
library(ggplot2)
library(ggimage)
library(dplyr)
library(png)
library(gridExtra)
library(grid)
```

```{r, echo=FALSE, warning=FALSE}
Sys.setenv("VROOM_CONNECTION_SIZE" = 5000000) # sets an environment variable to increase buffer size to accommodate a long line
```

```{r, echo=FALSE, warning=FALSE}
library(devtools)
devtools::install_github("abresler/nbastatR@aba9179ef644f263387c1536d6ddd26104d79cf4")
```

```{r, echo=FALSE}
# San Antonio Spurs, 2015-16 Season
spurs_shots_2016 <- nbastatR::teams_shots(teams = "San Antonio Spurs", 
  team_ids = 1610612759, 
  all_active_teams = F, 
  season_types = "Regular Season", 
  seasons = 2016, 
  measures = "FGA", 
  periods = 0, 
  months = 0, 
  date_from = NA, 
  date_to = NA, 
  nest_data = F, 
  return_message = T)
# San Antonio Spurs, 2016-17 Season
spurs_shots_2017 <- nbastatR::teams_shots(teams = "San Antonio Spurs", 
  team_ids = 1610612759, 
  all_active_teams = F, 
  season_types = "Regular Season", 
  seasons = 2017, 
  measures = "FGA", 
  periods = 0, 
  months = 0, 
  date_from = NA, 
  date_to = NA, 
  nest_data = F, 
  return_message = T)
# San Antonio Spurs, 2017-18 Season
spurs_shots_2018 <- nbastatR::teams_shots(teams = "San Antonio Spurs", 
  team_ids = 1610612759, 
  all_active_teams = F, 
  season_types = "Regular Season", 
  seasons = 2018, 
  measures = "FGA", 
  periods = 0, 
  months = 0, 
  date_from = NA, 
  date_to = NA, 
  nest_data = F, 
  return_message = T)
```
## 2018 San Antonio Spurs Shot Chart

```{r, echo=FALSE, warning=FALSE}
#1/2 Basketball Court Image Import
court_image_url <- "https://github.com/vsaulai/STAT-435-S25/raw/808a97692d03d5a8c4ef6cfd3b73d9cacd6d430f/290fc566ed83486e6f50979f535fb25e.jpg"
court_image <- image_read2(court_image_url, cut_empty_space = TRUE)
court_raster <- as.raster(court_image) #background court image line conversion
#2016 San Antonio Spurs: Shot Chart Map (scatter plot)
spurs_shots_2016_a <- spurs_shots_2016 %>%
  select(yearSeason, typeShot, locationX, locationY, distanceShot, isShotMade, distanceShot)
spurs_shots_2016_b <- spurs_shots_2016_a %>%
  select(yearSeason, locationX, locationY, distanceShot) %>%
  filter(distanceShot >= 2) #removed shots made from distance 0-1
spurs_shots_2016_shotmade <- spurs_shots_2016_a %>%
  select(locationX, locationY, typeShot)
spurs_shots_2016_xy <- spurs_shots_2016_b %>%
  select(locationX, locationY)
typeshot <- spurs_shots_2016_shotmade$typeShot

#2016 Shot Chart (scatter_plot)
shot_map_plot_16 <- ggplot(spurs_shots_2016_shotmade, aes(x = locationX, y = locationY, color = typeShot)) +
  annotation_custom(rasterGrob(court_raster, width = unit(1, "npc"), height = unit(1, "npc")), #background image import scaled
                    xmin = -265, xmax = 258, ymin = -45, ymax = 455) +
  geom_point(alpha = 0.3, size = 1) +
  scale_color_manual(values = c("2PT Field Goal" = "blue", "3PT Field Goal" = "red")) +
  ylim(-40, 700) +
  xlim(-280, 280) +
  theme_minimal() +
  labs(title = "2016 San Antonio Spurs: Shot Chart", x = NULL, y = NULL)

print(shot_map_plot_16)

```

## NBA Shot Charts Coordinate System
A basketball court's dimensions are measured at 94x50ft with the origin being at the center of the hoop,
from left to right (-250, 250) with each increment of 10's measuring to a feet. 
The y axis can also be measured between the ranges of (-40, 940).

```{r, echo=FALSE}
#2016 San Antonio Spurs: Shot Chart Map (scatter plot)
spurs_shots_2017_a <- spurs_shots_2017 %>%
  select(yearSeason, typeShot, locationX, locationY, distanceShot, isShotMade, distanceShot)
spurs_shots_2017_b <- spurs_shots_2017_a %>%
  select(yearSeason, locationX, locationY, distanceShot) %>%
  filter(distanceShot >= 2) #removed shots made from distance 0-1
spurs_shots_2017_type <- spurs_shots_2017_a %>%
  select(locationX, locationY, typeShot)
spurs_shots_2017_xy <- spurs_shots_2017_b %>%
  select(locationX, locationY)
typeshot_2 <- spurs_shots_2017_type$typeShot

#2017 Shot Chart (scatter_plot)
shot_map_plot_17 <- ggplot(spurs_shots_2017_type, aes(x = locationX, y = locationY, color = typeshot_2)) +
  annotation_custom(rasterGrob(court_raster, width = unit(1, "npc"), height = unit(1, "npc")), #background image import scaled
                    xmin = -265, xmax = 255, ymin = -47, ymax = 460) +
  geom_point(alpha = 0.3, size = 1) +
  scale_color_manual(values = c("2PT Field Goal" = "blue", "3PT Field Goal" = "red")) +
  ylim(-40, 700) +
  xlim(-280, 280) +
  theme_minimal() +
  labs(title = "2017 San Antonio Spurs: Shot Chart", x = NULL, y = NULL)

print(shot_map_plot_17)

```

## 2018 San Antonio Spurs Shot Chart

```{r, echo=FALSE}
#2018 San Antonio Spurs: Shot Chart Map (scatter plot)
spurs_shots_2018_a <- spurs_shots_2018 %>%
  select(yearSeason, typeShot, locationX, locationY, distanceShot, isShotMade, distanceShot)
spurs_shots_2018_b <- spurs_shots_2018_a %>%
  select(yearSeason, locationX, locationY, distanceShot) %>%
  filter(distanceShot >= 2) #removed shots made from distance 0-1
spurs_shots_2018_type <- spurs_shots_2018_a %>%
  select(locationX, locationY, typeShot)
spurs_shots_2018_xy <- spurs_shots_2018_b %>%
  select(locationX, locationY)

#2018 Shot Chart (scatter_plot)
shot_map_plot_18 <- ggplot(spurs_shots_2018_type, aes(x = locationX, y = locationY, color = spurs_shots_2018_type$typeShot)) +
  annotation_custom(rasterGrob(court_raster, width = unit(1, "npc"), height = unit(1, "npc")), #background image import scaled
                    xmin = -265, xmax = 255, ymin = -47, ymax = 460) +
  geom_point(alpha = 0.3, size = 1) +
  scale_color_manual(values = c("2PT Field Goal" = "blue", "3PT Field Goal" = "red")) +
  ylim(-40, 700) +
  xlim(-280, 280) +
  theme_minimal() +
  labs(title = "2018 San Antonio Spurs: Shot Chart", x = NULL, y = NULL)

print(shot_map_plot_18)
```

```{r}
#2016 Shot Chart Map (kernel_density_estimate_contour)
shot_map_16 <- ggplot(spurs_shots_2016_xy, aes(x = locationX, y = locationY)) +
  annotation_custom(rasterGrob(court_raster, width = unit(1, "npc"), height = unit(1, "npc")), #background image import scaled
                    xmin = -260, xmax = 252, ymin = -45, ymax = 472) +
  stat_density_2d(aes(fill = after_stat(level)), geom = "polygon", bins = 13, alpha = 0.8) +
  scale_fill_viridis_c() +
  ylim(-40, 700) +
  xlim(-280, 280) +
  theme_minimal() +
  labs(title = "2016 San Antonio Spurs: Density Level Shot Chart", x = NULL, y = NULL)

#2017 Shot Chart Map (kernel_density_estimate_contour)
shot_map_17 <- ggplot(spurs_shots_2017_xy, aes(x = locationX, y = locationY)) +
  annotation_custom(rasterGrob(court_raster, width = unit(1, "npc"), height = unit(1, "npc")), #background image import scaled
                    xmin = -260, xmax = 250, ymin = -47, ymax = 472) +
  stat_density_2d(aes(fill = after_stat(level)), geom = "polygon", bins = 13, alpha = 0.8) +
  scale_fill_viridis_c() +
  ylim(-40, 700) +
  xlim(-280, 280) +
  theme_minimal() +
  labs(title = "2017 San Antonio Spurs: Density Level Shot Chart", x = NULL, y = NULL)

#2018 Shot Chart Map (kernel_density_estimate_contour)
shot_map_18 <- ggplot(spurs_shots_2018_xy, aes(x = locationX, y = locationY)) +
  annotation_custom(rasterGrob(court_raster, width = unit(1, "npc"), height = unit(1, "npc")), #background image import scaled
                    xmin = -260, xmax = 250, ymin = -47, ymax = 472) +
  stat_density_2d(aes(fill = after_stat(level)), geom = "polygon", bins = 13, alpha = 0.8) +
  scale_fill_viridis_c() +
  ylim(-40, 700) +
  xlim(-280, 280) +
  theme_minimal() +
  labs(title = "2018 San Antonio Spurs: Density Level Shot Chart", x = NULL, y = NULL)

print(shot_map_16)
print(shot_map_17)
print(shot_map_18)
```

```{r, echo=FALSE}

```

